/* UI texts — mirrored from /texts.json (client copy for zero extra request) */
window.APP_TEXTS = {
  logo: 'Reminders',
  settingsTitle: 'Настройки',
  styleTitle: 'Настройки стиля',
  back: '← Назад',
  filterAll: 'Все',
  filterActive: 'Активные',
  filterDone: 'Отправленные',
  searchPlaceholder: 'Поиск по тексту…',
  emptyTitle: 'Пока нет напоминаний',
  emptyHint: 'Нажми «+» чтобы создать первое',
  emptySearch: 'Ничего не найдено',
  emptySearchHint: 'Попробуйте другой запрос',
  modalNew: 'Новое напоминание',
  modalEdit: 'Редактировать',
  labelTitle: 'Заголовок',
  labelText: 'Текст',
  labelDatetime: 'Дата и время',
  labelActive: 'Активно',
  placeholderTitle: 'Например: Позвонить маме',
  placeholderText: 'Подробности (необязательно)',
  cancel: 'Отмена',
  save: 'Сохранить',
  addAria: 'Добавить напоминание',
  settingsAria: 'Настройки',
  closeAria: 'Закрыть',
  editTitle: 'Редактировать',
  deleteTitle: 'Удалить',
  badgeActive: 'Активно',
  badgeSent: 'Отправлено',
  toastSaved: 'Сохранено ✨',
  toastDeleted: 'Удалено',
  toastStyleSaved: 'Стиль сохранён ✨',
  toastPreset: 'Пресет применён (сохраните чтобы оставить)',
  toastReset: 'Сброшено к тёмно-красному',
  toastLoadFail: 'Не удалось загрузить',
  toastSaveFail: 'Ошибка сохранения',
  toastNotFound: 'Напоминание не найдено',
  confirmDelete: 'Удалить это напоминание?',
  sectionColors: 'Цвета',
  sectionLayout: 'Оформление',
  sectionSnooze: 'Перенос напоминания',
  sectionPresets: 'Пресеты',
  labelBg: 'Фон',
  labelCard: 'Карточка',
  labelSurface: 'Поверхность',
  labelAccent: 'Акцент',
  labelAccentHover: 'Акцент (hover)',
  labelMuted: 'Приглушённый',
  labelBorder: 'Граница',
  labelRadius: 'Скругление',
  labelTransition: 'Скорость анимации',
  labelBlur: 'Размытие',
  labelGlass: 'Стекло (glass)',
  labelFont: 'Шрифт',
  labelSnoozeMinutes: 'Минут до повторного напоминания',
  btnReset: 'Сбросить',
  btnSaveStyle: 'Сохранить',
  presetDarkRed: 'Тёмно-красный',
  presetMidnight: 'Полночь',
  presetEmerald: 'Изумруд',
  presetViolet: 'Фиолет',
  presetOcean: 'Океан',
  presetLight: 'Светлый'
};
